### ISSUE TITLE
GUI: NullPointerException auf macOS

### ISSUE THREAD

**Issue by philippwinter** [Torridity/dsworkbench#29]
Die folgende Exception erscheint unter anderem beim Öffnen eines neuen Fensters. Ob der Fehler hier wirklich bei WB liegt, müsste man mal recherchieren.

`java.lang.NullPointerException
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:630)
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:639)
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:639)
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:639)
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:639)
	at sun.lwawt.macosx.CAccessibility._addChildren(CAccessibility.java:639)
	at sun.lwawt.macosx.CAccessibility.access$000(CAccessibility.java:40)
	at sun.lwawt.macosx.CAccessibility$33.call(CAccessibility.java:575)
	at sun.lwawt.macosx.CAccessibility$33.call(CAccessibility.java:572)
	at sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(LWCToolkit.java:597)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by extremeCrazyCoder** [comment]
Beim Starten von WB erscheint unter Linux auch so eine Meldung beim Fenster öffnen habe ich bisher noch keine gehabt (alles nur auf der Kommandozeile)

**Comment by philippwinter** [comment]
Ja, geloggt wird sie auf der Kommandozeile; allerdings konnte ich bisher zumindest eine große Korrelation beim Auftauchen der Meldung mit dem Öffnen eines Fensters herstellen.

**Comment by extremeCrazyCoder** [comment]
achso

Ich habe eine andere:

`java.lang.NullPointerException
	at javax.swing.plaf.metal.MetalSliderUI.installUI(MetalSliderUI.java:110)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at com.jidesoft.swing.RangeSlider.updateUI(RangeSlider.java:90)
	at javax.swing.JSlider.<init>(JSlider.java:275)
	at javax.swing.JSlider.<init>(JSlider.java:198)
	at com.jidesoft.swing.RangeSlider.<init>(RangeSlider.java:45)
	at de.tor.tribes.ui.views.DSWorkbenchDistanceFrame.buildMenu(DSWorkbenchDistanceFrame.java:180)
	at de.tor.tribes.ui.views.DSWorkbenchDistanceFrame.<init>(DSWorkbenchDistanceFrame.java:113)
	at de.tor.tribes.ui.views.DSWorkbenchDistanceFrame.getSingleton(DSWorkbenchDistanceFrame.java:90)
	at de.tor.tribes.ui.windows.DSWorkbenchMainFrame.serverSettingsChangedEvent(DSWorkbenchMainFrame.java:590)
	at de.tor.tribes.ui.windows.DSWorkbenchMainFrame.init(DSWorkbenchMainFrame.java:677)
	at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.hideSplash(DSWorkbenchSplashScreen.java:361)
	at de.tor.tribes.ui.windows.HideSplashTask.run(DSWorkbenchSplashScreen.java:572)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

Bei neuen Fenstern bekomme ich allerdings keine

**Comment by philippwinter** [comment]
Interessant. Werden bei dir diese Exceptions in das Log-File geschrieben? Ich habe leider das Gefühl, dass die log4j Konfiguration bei mir nicht zur Anwendung kommt, sondern immer nur Exceptions auf stderr geschrieben werden.

**Comment by extremeCrazyCoder** [comment]
nein ebenfalls nur auf stderr

**Comment by extremeCrazyCoder** [comment]
gerade habe ich gesehen, dass meine Nullpointer als WARN deklariert wird:

`2017-02-16 23:26:12,544 - WARN  - Launcher             (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [413]) - Unhandled exception in thread 'AWT-EventQueue-0'
java.lang.IllegalArgumentException: component and container should be in the same top-level window
	at java.awt.Container.checkAdding(Container.java:525)
	at java.awt.Container.setComponentZOrder(Container.java:766)
	at com.jidesoft.plaf.basic.BasicJideTabbedPaneUI$ScrollableTabSupport.stateChanged(BasicJideTabbedPaneUI.java:7920)
	at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
	at javax.swing.JViewport$ViewListener.componentResized(JViewport.java:1288)
	at java.awt.Component.processComponentEvent(Component.java:6359)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Torridity** [comment]
Solche Meldungen würde ich grundsätzlich nicht DS WB zuordnen. Ja, es gibt auch Bugs in diversen JDKs und JREs. ;-) 
Weiterhin gilt, dass nur Log4j Events vom DS WB Logging behandelt werden. Loggt ein Library oder eben die Laufzeit woanders hin, kann trotzdem Ouput im Terminal auftauchen.

Den ursprünglichen Fehler in dem Issue finde ich im Zusammenhang mit OpenJDK, vllt. hilft ja Oracle JDK sofern man bei so einem eher unkritischen Fehler Hilfe braucht.

**Comment by extremeCrazyCoder** [comment]
Das sollte man dann auch schließen können, nachdem diese Fehler eher unauffindbar sind (und wie du gesagt hast vermutl. nicht mal von WB kommen
