### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by georgkrause** [Torridity/dsworkbench#5]
java.lang.RuntimeException: Initialization failed
	at de.tor.tribes.ui.windows.DSWorkbenchMainFrame.serverSettingsChangedEvent(DSWorkbenchMainFrame.java:671)
	at de.tor.tribes.ui.windows.DSWorkbenchMainFrame.init(DSWorkbenchMainFrame.java:708)
	at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.hideSplash(DSWorkbenchSplashScreen.java:401)
	at de.tor.tribes.ui.windows.HideSplashTask.run(DSWorkbenchSplashScreen.java:613)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
	at de.tor.tribes.io.ServerManager.getServerURL(ServerManager.java:106)
	at de.tor.tribes.types.Attack.getReplacements(Attack.java:380)
	at de.tor.tribes.util.bb.AttackListFormatter.formatElements(AttackListFormatter.java:42)
	at de.tor.tribes.ui.windows.BBCodeEditor.fireExportTypeChangedEvent(BBCodeEditor.java:518)
	at de.tor.tribes.ui.windows.BBCodeEditor.<init>(BBCodeEditor.java:135)
	at de.tor.tribes.ui.windows.BBCodeEditor.getSingleton(BBCodeEditor.java:110)
	at de.tor.tribes.ui.windows.DSWorkbenchMainFrame.serverSettingsChangedEvent(DSWorkbenchMainFrame.java:633)
	... 5 more

**Comment by Torridity** [comment]
Welche DS Workbench Version verwendest du? Tritt der Fehler mit der aktuellen Version 3.42 auf?

**Comment by georgkrause** [comment]
War 3.3

Am So. Jan. 3 15:42:35 2016 GMT+0100 schrieb Torridity:

**Comment by Torridity** [comment]
Alles unter 3.4 funktioniert nicht mehr. Bitte die Version aktualisieren, dann sollte es wie gewohnt wieder laufen.
