### ISSUE TITLE
Installation: Keine Server gefunden. (Servereinstellungen)

### ISSUE THREAD

**Issue by DerSebi0815** [Torridity/dsworkbench#58]
Moin,

hab's jetzt mehrmals von verschiedenen Rechnern probiert und nirgends hinbekommen...
Jedes mal stockt bei mir die Installation bei den Servereinstellungen, mit der Meldung:
"Keine Server gefunden. Bitte versuch es später noch einmal." 
Mehrere Rechner probiert, immer verschiedene Verbindungen zum Internet.

Sicher irgendwas total simples...helft mir mal auf die Sprünge.
Oder ist das aktuell ein bekanntes Problem?

Gruß
Sebi

**Comment by extremeCrazyCoder** [comment]
Falls du https://github.com/Torridity/dsworkbench/releases/tag/3.62 verwendest ein bekanntes Problem von Java 9 + / Mac

Gibt allerdings schon einen Patch:
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.62_beta_4

**Comment by DerSebi0815** [comment]
Bisher nur Win7 oder Win10 dafür genutzt...Mit der Beta geht es leider auch nicht weiter.

**Comment by extremeCrazyCoder** [comment]
kannst du die Beta bitte mal über das DSWorkbench-Debug.bat file starten und mir dann den Log schicken?

dann müsste ich sehen können woran es liegt

**Comment by DerSebi0815** [comment]
Das in C:\Windows\System32\log oder das hier?
```
2018-08-15 23:47:31,833 main DEBUG Initializing configuration XmlConfiguration[location=C:\Program Files\DSWorkbench\log4j-debug.xml]
2018-08-15 23:47:31,849 main DEBUG Installed 1 script engine
2018-08-15 23:47:32,277 main DEBUG Oracle Nashorn version: 1.8.0_181, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
2018-08-15 23:47:32,277 main DEBUG PluginManager 'Core' found 116 plugins
2018-08-15 23:47:32,277 main DEBUG PluginManager 'Level' found 0 plugins
2018-08-15 23:47:32,292 main DEBUG PluginManager 'Lookup' found 13 plugins
2018-08-15 23:47:32,292 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2018-08-15 23:47:32,308 main TRACE TypeConverterRegistry initializing.
2018-08-15 23:47:32,308 main DEBUG PluginManager 'TypeConverter' found 26 plugins
2018-08-15 23:47:32,339 main DEBUG PatternLayout$Builder(pattern="%d - %-5p [%t] - (%C [%L]) - %m%n", PatternSelector=null, Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2018-08-15 23:47:32,339 main DEBUG PluginManager 'Converter' found 44 plugins
2018-08-15 23:47:32,355 main DEBUG Building Plugin[name=OnStartupTriggeringPolicy, class=org.apache.logging.log4j.core.appender.rolling.OnStartupTriggeringPolicy].
2018-08-15 23:47:32,371 main DEBUG createPolicy(minSize="1")
2018-08-15 23:47:32,371 main DEBUG Building Plugin[name=SizeBasedTriggeringPolicy, class=org.apache.logging.log4j.core.appender.rolling.SizeBasedTriggeringPolicy].
2018-08-15 23:47:32,371 main DEBUG createPolicy(size="50 MB")
2018-08-15 23:47:32,371 main DEBUG Building Plugin[name=Policies, class=org.apache.logging.log4j.core.appender.rolling.CompositeTriggeringPolicy].
2018-08-15 23:47:32,371 main DEBUG createPolicy(={OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=52428800)})
2018-08-15 23:47:32,371 main DEBUG Building Plugin[name=IfFileName, class=org.apache.logging.log4j.core.appender.rolling.action.IfFileName].
2018-08-15 23:47:32,371 main DEBUG createNameCondition(glob="log/dsworkbench.*.log.gz", regex="null", ={})
2018-08-15 23:47:32,386 main DEBUG Building Plugin[name=IfLastModified, class=org.apache.logging.log4j.core.appender.rolling.action.IfLastModified].
2018-08-15 23:47:32,386 main DEBUG createAgeCondition(age="P7D", ={})
2018-08-15 23:47:32,386 main TRACE Using default SystemClock for timestamps.
2018-08-15 23:47:32,386 main DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
2018-08-15 23:47:32,386 main DEBUG Building Plugin[name=Delete, class=org.apache.logging.log4j.core.appender.rolling.action.DeleteAction].
2018-08-15 23:47:32,386 main DEBUG createDeleteAction(basePath="${baseDir}", followLinks="false", maxDepth="1", testMode="false", PathSorter=null, ={IfFileName(glob:log/dsworkbench.*.log.gz), IfLastModified(age=P7D)}, ScriptCondition=null, Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml))
2018-08-15 23:47:32,386 main DEBUG Building Plugin[name=DefaultRolloverStrategy, class=org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy].
2018-08-15 23:47:32,402 main DEBUG DefaultRolloverStrategy$Builder(max="null", min="null", fileIndex="null", compressionLevel="null", ={DeleteAction[basePath=${baseDir}, options=[], maxDepth=1, conditions=[IfFileName(glob:log/dsworkbench.*.log.gz), IfLastModified(age=P7D)]]}, stopCustomActionsOnError="null", tempCompressedFilePattern="null", Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml))
2018-08-15 23:47:32,402 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.RollingFileAppender].
2018-08-15 23:47:32,418 main DEBUG RollingFileAppender$Builder(fileName="log/dsworkbench.log", filePattern="log/dsworkbench.%i.log.gz", append="null", locking="null", Policies(CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=52428800)])), DefaultRolloverStrategy(DefaultRolloverStrategy(min=1, max=7, useMax=true)), advertise="null", advertiseUri="null", createOnDemand="null", filePermissions="null", fileOwner="null", fileGroup="null", bufferedIo="null", bufferSize="null", immediateFlush="null", ignoreExceptions="false", PatternLayout(%d - %-5p [%t] - (%C [%L]) - %m%n), name="MAINFILE", Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml), Filter=null)
2018-08-15 23:47:32,433 main TRACE New file 'log/dsworkbench.log' created = false
2018-08-15 23:47:32,433 main DEBUG Starting RollingFileManager log/dsworkbench.log
2018-08-15 23:47:32,433 main DEBUG PluginManager 'FileConverter' found 2 plugins
2018-08-15 23:47:32,449 main DEBUG Setting prev file time to 2018-08-15T23:41:36.962+0200
2018-08-15 23:47:32,449 main DEBUG Initializing triggering policy CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=52428800)])
2018-08-15 23:47:32,449 main TRACE Using default SystemClock for timestamps.
2018-08-15 23:47:32,449 main DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
2018-08-15 23:47:32,464 main TRACE DefaultRolloverStrategy.purge() took 15.0 milliseconds
2018-08-15 23:47:32,464 main DEBUG RollingFileManager executing synchronous FileRenameAction[log\dsworkbench.log to log\dsworkbench.2.log, renameEmptyFiles=false]
2018-08-15 23:47:32,480 main TRACE Renamed file C:\WINDOWS\system32\log\dsworkbench.log to C:\WINDOWS\system32\log\dsworkbench.2.log with Files.move
2018-08-15 23:47:32,480 main DEBUG RollingFileManager executing async CompositeAction[GzCompressAction[log\dsworkbench.2.log to log\dsworkbench.2.log.gz, deleteSource=true], DeleteAction[basePath=${baseDir}, options=[], maxDepth=1, conditions=[IfFileName(glob:log/dsworkbench.*.log.gz), IfLastModified(age=P7D)]]]
2018-08-15 23:47:32,480 main DEBUG Now writing to log/dsworkbench.log at 2018-08-15T23:47:32.480+0200
2018-08-15 23:47:32,480 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2018-08-15 23:47:32,480 main DEBUG PatternLayout$Builder(pattern="%d - %-5p [%t] - (%C [%L]) - %m%n", PatternSelector=null, Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2018-08-15 23:47:32,496 Log4j2-TF-1-RollingFileManager-1 DEBUG Starting DeleteAction[basePath=${baseDir}, options=[], maxDepth=1, conditions=[IfFileName(glob:log/dsworkbench.*.log.gz), IfLastModified(age=P7D)]]
2018-08-15 23:47:32,496 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.ConsoleAppender].
2018-08-15 23:47:32,496 main DEBUG ConsoleAppender$Builder(target="SYSTEM_OUT", follow="null", direct="null", bufferedIo="null", bufferSize="null", immediateFlush="null", ignoreExceptions="null", PatternLayout(%d - %-5p [%t] - (%C [%L]) - %m%n), name="STDOUT", Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml), Filter=null)
2018-08-15 23:47:32,511 main DEBUG Starting OutputStreamManager SYSTEM_OUT.false.false
2018-08-15 23:47:32,511 main DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2018-08-15 23:47:32,511 main DEBUG createAppenders(={MAINFILE, STDOUT})
2018-08-15 23:47:32,511 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2018-08-15 23:47:32,511 main DEBUG createAppenderRef(ref="STDOUT", level="null", Filter=null)
2018-08-15 23:47:32,511 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2018-08-15 23:47:32,511 main DEBUG createAppenderRef(ref="MAINFILE", level="null", Filter=null)
2018-08-15 23:47:32,511 main DEBUG Building Plugin[name=root, class=org.apache.logging.log4j.core.config.LoggerConfig$RootLogger].
2018-08-15 23:47:32,527 main DEBUG createLogger(additivity="null", level="TRACE", includeLocation="null", ={STDOUT, MAINFILE}, ={}, Configuration(C:\Program Files\DSWorkbench\log4j-debug.xml), Filter=null)
2018-08-15 23:47:32,527 main DEBUG Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
2018-08-15 23:47:32,527 main DEBUG createLoggers(={root})
2018-08-15 23:47:32,527 main DEBUG Configuration XmlConfiguration[location=C:\Program Files\DSWorkbench\log4j-debug.xml] initialized
2018-08-15 23:47:32,542 main DEBUG Starting configuration XmlConfiguration[location=C:\Program Files\DSWorkbench\log4j-debug.xml]
2018-08-15 23:47:32,542 main DEBUG Started configuration XmlConfiguration[location=C:\Program Files\DSWorkbench\log4j-debug.xml] OK.
2018-08-15 23:47:32,542 main TRACE Stopping org.apache.logging.log4j.core.config.DefaultConfiguration@27ddd392...
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration notified 1 ReliabilityStrategies that config will be stopped.
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration stopping root LoggerConfig.
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration notifying ReliabilityStrategies that appenders will be stopped.
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration stopping remaining Appenders.
2018-08-15 23:47:32,542 main DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false-1
2018-08-15 23:47:32,542 main DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false-1, all resources released: true
2018-08-15 23:47:32,542 main DEBUG Appender DefaultConsole-1 stopped with status true
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration stopped 1 remaining Appenders.
2018-08-15 23:47:32,542 main TRACE DefaultConfiguration cleaning Appenders from 1 LoggerConfigs.
2018-08-15 23:47:32,542 main DEBUG Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@27ddd392 OK
2018-08-15 23:47:32,605 main TRACE Reregistering MBeans after reconfigure. Selector=org.apache.logging.log4j.core.selector.ClassLoaderContextSelector@69997e9d
2018-08-15 23:47:32,621 main TRACE Reregistering context (1/1): '14ae5a5' org.apache.logging.log4j.core.LoggerContext@793be5ca
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5'
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=StatusLogger'
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=ContextSelector'
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=Loggers,name=*'
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=Appenders,name=*'
2018-08-15 23:47:32,621 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=AsyncAppenders,name=*'
2018-08-15 23:47:32,636 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=AsyncLoggerRingBuffer'
2018-08-15 23:47:32,636 main TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=14ae5a5,component=Loggers,name=*,subtype=RingBuffer'
2018-08-15 23:47:32,636 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5
2018-08-15 23:47:32,636 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5,component=StatusLogger
2018-08-15 23:47:32,636 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5,component=ContextSelector
2018-08-15 23:47:32,652 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5,component=Loggers,name=
2018-08-15 23:47:32,652 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5,component=Appenders,name=MAINFILE
2018-08-15 23:47:32,652 main DEBUG Registering MBean org.apache.logging.log4j2:type=14ae5a5,component=Appenders,name=STDOUT
2018-08-15 23:47:32,652 main TRACE Using DummyNanoClock for nanosecond timestamps.
2018-08-15 23:47:32,652 main DEBUG Reconfiguration complete for context[name=14ae5a5] at URI C:\Program Files\DSWorkbench\log4j-debug.xml (org.apache.logging.log4j.core.LoggerContext@793be5ca) with optional ClassLoader: null
2018-08-15 23:47:32,652 main DEBUG Shutdown hook enabled. Registering a new one.
2018-08-15 23:47:32,652 main DEBUG LoggerContext[name=14ae5a5, org.apache.logging.log4j.core.LoggerContext@793be5ca] started OK.
2018-08-15 23:47:32,714 - DEBUG [main] - (de.tor.tribes.util.GlobalDefaults [51]) - Loading defaults
2018-08-15 23:47:32,902 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [98]) - Loading help system
2018-08-15 23:47:32,902 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [177]) - HelpSet found
2018-08-15 23:47:32,933 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [185]) - HelpSet opened
2018-08-15 23:47:32,933 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [188]) - Creating HelpBroker
2018-08-15 23:47:32,996 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [193]) - Creating DisplayHelpFromSource
2018-08-15 23:47:32,996 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [197]) - HelpSystem initialized
2018-08-15 23:47:32,996 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [100]) - Loading properties
2018-08-15 23:47:32,996 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [222]) - Loading existing properties file
2018-08-15 23:47:32,996 - DEBUG [main] - (de.tor.tribes.util.GlobalOptions [102]) - Loading graphic pack
2018-08-15 23:47:33,011 - ERROR [main] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [494]) - Failed to setup LnF
java.lang.Exception: Fehler beim laden des Grafikpaketes
        at de.tor.tribes.util.Skin.loadSkin(Skin.java:224) ~[Core-3.62.jar:3.62]
        at de.tor.tribes.util.Skin.<init>(Skin.java:110) ~[Core-3.62.jar:3.62]
        at de.tor.tribes.util.GlobalOptions.loadSkin(GlobalOptions.java:289) ~[Core-3.62.jar:3.62]
        at de.tor.tribes.util.GlobalOptions.initialize(GlobalOptions.java:103) ~[Core-3.62.jar:3.62]
        at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.main(DSWorkbenchSplashScreen.java:491) [Core-3.62.jar:3.62]
Caused by: javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source) ~[?:1.8.0_181]
        at de.tor.tribes.util.ImageUtils.loadImage(ImageUtils.java:128) ~[Core-3.62.jar:3.62]
        at de.tor.tribes.util.Skin.loadSkin(Skin.java:185) ~[Core-3.62.jar:3.62]
        ... 4 more
2018-08-15 23:47:34,352 - DEBUG [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [210]) - Starting first start wizard
2018-08-15 23:47:34,352 - DEBUG [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [214]) -  - Initializing first start wizard
2018-08-15 23:47:34,367 - DEBUG [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [220]) -  - Showing wizard
2018-08-15 23:47:34,680 - DEBUG [StartupTimer] - (de.tor.tribes.ui.wiz.FirstStartWizard [48]) - Returning welcome page
2018-08-15 23:47:37,398 - DEBUG [AWT-EventQueue-0] - (de.tor.tribes.ui.wiz.FirstStartWizard [51]) - Returning network page
2018-08-15 23:47:41,492 - DEBUG [AWT-EventQueue-0] - (de.tor.tribes.ui.wiz.FirstStartWizard [54]) - Returning server settings page
2018-08-15 23:47:41,507 - DEBUG [AWT-EventQueue-0] - (de.tor.tribes.io.ServerManager [58]) - Reading servers from servers.txt
2018-08-15 23:47:41,507 - ERROR [AWT-EventQueue-0] - (de.tor.tribes.ui.wiz.ServerSettings [70]) - Fehler bei der Server suche
java.lang.Exception: Keine / Leere listelen: 0
        at de.tor.tribes.ui.wiz.ServerSettings.<init>(ServerSettings.java:56) [Core-3.62.jar:3.62]
        at de.tor.tribes.ui.wiz.FirstStartWizard.createPanel(FirstStartWizard.java:55) [Core-3.62.jar:3.62]
        at org.netbeans.spi.wizard.SimpleWizardInfo.createPanel(SimpleWizardInfo.java:112) [wizard-1.0.jar:?]
        at org.netbeans.spi.wizard.SimpleWizard.navigatingTo(SimpleWizard.java:109) [wizard-1.0.jar:?]
        at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137) [wizard-1.0.jar:?]
        at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:475) [wizard-1.0.jar:?]
        at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:369) [wizard-1.0.jar:?]
        at org.netbeans.api.wizard.displayer.NavButtonManager.processNext(NavButtonManager.java:354) [wizard-1.0.jar:?]
        at org.netbeans.api.wizard.displayer.NavButtonManager.actionPerformed(NavButtonManager.java:254) [wizard-1.0.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_181]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_181]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_181]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_181]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:1.8.0_181]
        at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_181]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_181]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_181]
        at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_181]
        at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_181]
        at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_181]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_181]
2018-08-15 23:48:48,946 - DEBUG [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [222]) - Wizard finished with result null
2018-08-15 23:48:48,946 - DEBUG [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [227]) -  - Wizard has finished
2018-08-15 23:48:48,946 - WARN  [StartupTimer] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen [229]) -  - Wizard returned no result. Startup will fail.
```

**Comment by extremeCrazyCoder** [comment]
genau das was du geschickt hast

nach genauerer Betrachtung sehe ich da 2 Probleme:
1) Scheinst du nicht alles enpackt zu haben, weil die server.txt leer ist & auch das laden des Grafikpakets fehlschlägt
2) Ist derzeit C:\Programme keine gute Position für Workbench, weil es in seinem eigenen Verzeichnis Schreibberechtigungen benötigt. Besser wäre z.B. Downloads / Eigene Dorkumente (generell funktionieren alle Unterverzeichnisse von C:\Users\{dein Benutzername}

**Comment by extremeCrazyCoder** [comment]
1. ist auch das Problem, warum du keine Server siehst

**Comment by DerSebi0815** [comment]
Also jetzt gehts...habe es nochmal so gemacht wie bisher auch, nur vom Downloads Ordner aus.

Kanns sein das man das auch nicht als Admin ausführen darf?

**Comment by extremeCrazyCoder** [comment]
ich wüsste nicht warum man das nicht tuen dürfte
ist aber nicht Sinn der Sache, dass man einfach irgendein Programm mit Admin rechten laufen lässt

**Comment by extremeCrazyCoder** [comment]
@Torridity das hier dürfte erledigt sein bitte schließen
