### ISSUE TITLE
Beute Parsen

### ISSUE THREAD

**Issue by Teifun2** [Torridity/dsworkbench#60]
Ich bin mir nicht ganz sicher ob das nur bei mir so ist, aber im moment wird bei mir keine Beute geparst. Oder zumindest wird mir bei den berichten nicht angezeigt das diese eingelesen wurden. Auch erspähte Rohstoffe werden im Farmmanager nicht richtig angezeigt.
Ich hab kurz über den Parser geschaut und konnte so über Github nicht erkennen woran das liegen könnte. 

Hat jemand anderes auch dieses Problem oder liegt das nur bei mir? Bin auf deutschen Servern.
Falls das ein aktives problem sein sollte kann ich sonst schon mal den code debuggen. Wollte mich nur nicht reinschmeissen und dann merken das es irgend ein Problem von meinem Setup ist.

Lg Linard

**Comment by extremeCrazyCoder** [comment]
Welche Version benutzt du?

Ich muss mir das noch bisschen ansehen. Ich hab gerade probiert einen Bericht zu parsen. Über den Obst Server ging es aber über Strg+C nicht (also das einlesen generell). Beute hab ich in der Vorschau keine gesehen...

Hast ein gutes Timing, weil ich eh gerade dabei bin die letzten Bugs aus der aktuellen Dev Version rauszuschmeißen, damit es endlich eine offizielle Version gibt die unter Java 9+ läuft

**Comment by extremeCrazyCoder** [comment]
ok Debuggen hat ergeben, dass ich selber schuld bin, dass das Bericht einlesen nicht klappt :smile: 
Ich hab die internen Namen der Gebäude geändert (damit ich mir die Infos über die Gebäude von der buildings.xml von DS laden kann), dabei aber vergessen den Namen auch in den .parserprop Files auszubessern...

Die Beute wurde dannach korrekt eingelensen, daher weiß ich nicht woran es bei dir konkret liegt. Falls du die version V3.62 verwendest, kann es sein, dass es darin nicht geht. Nachdem es seit der Version schon riesige Änderungen gegeben hat schätze ich, dass es irgendwo gefixt wurde.

Nur als Info (Falls du das meinst):
Die eingelesenen Infos werden in der Berichtsvorschau nicht angezeigt (weiß ich auch nicht warum) in dem reports.xml File in deinem Profil Directory sind sie aber drinnen.

Wenn du Lust hast kannst du da gerne etwas basteln, dass diese Infos auch angezeigt werden :smiley:

PS. ich sehe gerade im Commit habe ich den falschen Commit referenziert. Ich wollte  f8677fd092551e7d8e0d4aaa659955fb2d3e1ae5 referenzieren

**Comment by Teifun2** [comment]
Ja ich benutze version 3.62. Ich habe auch kurz im reports.xml nachgeschaut und da sind keine ressourcen drin. Sollte es denn mit deinem neuen Fix jetzt Funktionieren? Wann wird das in einen Release gepackt oder soll ich es mir besser einfach selber bilden?

Danke für die schnelle hilfe :)

**Comment by Teifun2** [comment]
OK ich werds mal anschauen. Ich hab da noch ein par kleine Fragen. Auf welcher Java version läuft dein momentaner Build? JDK9 oder geht es auch mit JDK11?
Kann mann das Programm auch von ner IDE (Intellij o.ä.) starten und wenn ja wie? Ich hab es versucht aber es scheint alls wären die ressourcen nicht richtig eingebunden. Wenn ich den Maven build mache klappt es besser.

**Comment by extremeCrazyCoder** [comment]
Ich entwickle derzeit unter Netbeans da kann ich auf das Hauptprojet drauf drücken und dann Assembly:Assembly sagen.
Einzelne Files kann ich auch über "Run this File" starten (gibt aber dann glaub ich die von dir genannten Probleme mit den resourcen)

Gebuildet wird bei maven mit JDK8 laufen sollte es unter jeder (ich nutze 11). Das gilt aber nur ab beta_4 davor läuft es nur unter Java 8
Falls du Ideen hast wie man das mit dem Build besser machen kann dann änder es ruhig :)
Ich glaube auch das es sinnlos ist, dass wir ein eigenes Modul für die Parser haben

**Comment by Teifun2** [comment]
Wieso ist das modul für den Parser abgekoppelt?

**Comment by extremeCrazyCoder** [comment]
Ich weiß nicht vielleicht war irgendwann mal angedacht, dass sich die Parser nicht bei jeder release ändern, oder dass sie sich schneller entwickeln...

**Comment by Teifun2** [comment]
Ich schaffe es nicht einen funktionierenden Build zu machen. (Master Branch). Gewisse Poms's für den maven assembly scheinen zu fehlen :/

`[INFO] --- maven-assembly-plugin:2.5.5:assembly (default-cli) @ dsworkbench ---
[INFO] Reading assembly descriptor: src/main/assemble/distribution.xml
[WARNING] Missing POM for de.tor:dssim:jar:1.36
[WARNING] Missing POM for de.tor:help:jar:1.0
[WARNING] Missing POM for netbeans:wizard:jar:1.0
[WARNING] Missing POM for php-parser:php-parser:jar:0.3
[WARNING] Missing POM for bislider:bislider:jar:1.0
[WARNING] Missing POM for colorchooser:colorchooser:jar:1.0
[WARNING] Cannot include project artifact: de.tor.dswb:dsworkbench:pom:3.62; it doesn't have an associated file or directory.
[INFO] Copying files to /.../GitKraken/dsworkbench/release/DSWorkbench-3.62
[WARNING] Assembly file: /.../dsworkbench/release/DSWorkbench-3.62 is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[WARNING] Cannot include project artifact: de.tor.dswb:dsworkbench:pom:3.62; it doesn't have an associated file or directory.
[INFO] Building zip: /.../dsworkbench/release/DSWorkbench-3.62.zip`

Weisst du wie ich das fixen kann? oder kannst du mir für den ersten moment mal einen funktionierenden build des master geben?

Lg Teifun2

**Comment by extremeCrazyCoder** [comment]
Hat es bei dir funktioniert?

**Comment by Teifun2** [comment]
Ich schaffe es nicht deinen Build zum laufen zu kriegen. Auch nicht wenn ich es selbe builde. Beim Splashscreen commt immer ein StackTracke von wegen loadData() ist fehlgeschlagen. Ich bin mir nicht sicher ob es daran liegt das es die falsche java version benutzt. Ich werde es nochmals versuchen. Falls es dann nicht klappt kann ich dir den StackTrace zeigen.

**Comment by Teifun2** [comment]
Ok ich habs gerade nochmals ganz sicher mit Java 11 versucht. hier ist der Fehler:

```
java.lang.Exception: loadData() returned 'false'. See log for more details.
	at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.hideSplash(DSWorkbenchSplashScreen.java:355)
	at de.tor.tribes.ui.windows.HideSplashTask.run(DSWorkbenchSplashScreen.java:551)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by extremeCrazyCoder** [comment]
Erstmal es sollte egal sein mit welcher Version du es aufmachst. Ich hab nur gesagt, dass es auch mit Java 11 gehen sollte.
Mit Java 8 ist es auf jeden Fall auch kompatibel.

Zur Meldung: Die Meldung ist nichts sagend...

Kannst du bitte im Debugging Modus starten und dann die Log Output (kurz) vor dem Fehler reinstellen (dazu das .bat / Shell Skript mit Debugging im Namen ausführen)

Eine Idee habe ich woher das kommen könnte: Ich habe dort in der Gegend den Gebäude-Server-Manager eingefügt. Wenn der Fehlschlägt kann es solche Fehler geben. Ich werde das Mal mit einer. Neuinstallation testen. Der ganze Code dort ist leider etwas unübersichtlich, wodurch ich nicht genau weiß ob ich das richtig eingefügt habe.

**Comment by Teifun2** [comment]
Jawoll schein ein Problem mit diesen BuildingSettings zu sein:

```
2019-01-30 16:21:33,518 - ERROR [StartupTimer] - (de.tor.tribes.util.BuildingSettings [108]) - Failed to load buildings
java.io.FileNotFoundException: ./servers/de162/buildings.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_191]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_191]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_191]
	at de.tor.tribes.util.xml.JDomUtils.getDocument(JDomUtils.java:48) ~[Core-3.62.jar:3.62]
	at de.tor.tribes.util.BuildingSettings.loadSettings(BuildingSettings.java:78) [Core-3.62.jar:3.62]
	at de.tor.tribes.io.DataHolder.serverSupported(DataHolder.java:187) [Core-3.62.jar:3.62]
	at de.tor.tribes.io.DataHolder.loadData(DataHolder.java:231) [Core-3.62.jar:3.62]
	at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.hideSplash(DSWorkbenchSplashScreen.java:354) [Core-3.62.jar:3.62]
	at de.tor.tribes.ui.windows.HideSplashTask.run(DSWorkbenchSplashScreen.java:551) [Core-3.62.jar:3.62]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]
2019-01-30 16:21:33,520 - ERROR [StartupTimer] - (de.tor.tribes.io.DataHolder [200]) - Failed to check server settings
java.lang.Exception: Failed to load buildings
	at de.tor.tribes.io.DataHolder.serverSupported(DataHolder.java:188) [Core-3.62.jar:3.62]
	at de.tor.tribes.io.DataHolder.loadData(DataHolder.java:231) [Core-3.62.jar:3.62]
	at de.tor.tribes.ui.windows.DSWorkbenchSplashScreen.hideSplash(DSWorkbenchSplashScreen.java:354) [Core-3.62.jar:3.62]
	at de.tor.tribes.ui.windows.HideSplashTask.run(DSWorkbenchSplashScreen.java:551) [Core-3.62.jar:3.62]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]
2019-01-30 16:21:33,521 - ERROR [StartupTimer] - (de.tor.tribes.io.DataHolder [305]) - Failed to read server settings
2019-01-30 16:21:33,522 - INFO  [StartupTimer] - (de.tor.tribes.util.GlobalOptions [135]) - Internal data markes as 'DAMAGED'
```

**Comment by extremeCrazyCoder** [comment]
hm ok mist

dann kannst du nur mit diesem Commit builden: https://github.com/extremeCrazyCoder/dsworkbench/commit/4ad11c7de307494055b4f12492d5a8b19fe1395c

da sollte dein Problem auch behoben sein. Ich werde dann morgen / übermorgen mir das ganze nochmal ansehen wo ich das kopieren vom buildings.xml veranlassen müsste

wenn du dennoch die Version starten willst, dann müsste es gehen indem du die buildings_tmp.xml aus dem Hauptordner in den server/de162 Ordner kopierst

**Comment by extremeCrazyCoder** [comment]
so ist jetzt gefixt
das ganze gefällt mir aber nicht, daher werde ich das dann in nächster Zeit noch neu schreiben. Ich will jetzt aber nicht damit das nächste release rauszögern, daher steht das eher weiter hinten auf der Prioritätenliste

**Comment by extremeCrazyCoder** [comment]
wenn du noch was findest dann sag Bescheid (oder es bei dir immer noch nicht funktioniert)

Ich teste immer mit den "alten" Daten von mir und und führe nicht bei jedem Build eine neu installation aus, daher fallen mir solche Fehler nur selten auf. Vor dem Release hätte ich das aber nochmal getestet

**Comment by extremeCrazyCoder** [comment]
wie sieht es denn mit der neuen Version aus?

**Comment by extremeCrazyCoder** [comment]
@Torridity auch das hier sieht fertig aus
