### ISSUE TITLE
farmmanager

### ISSUE THREAD

**Issue by xeddix** [Torridity/dsworkbench#65]
Hallo,

tut mir leid das ich doch noch mal fragen muss

funktioniert WB wieder so das man die Berichte mit zum bspl. "E"
einlesen kann also mit einem Tastendruck,

früher ging das ja prima aber ich bekomme das jetzt nicht mehr hin und
so mehr ich im Forum nachlese umso weniger verstehe ich

gruss

edmund

**Comment by extremeCrazyCoder** [comment]
Hallo,

ich spiele selber nicht mehr aktiv, daher kann ich es nicht garantieren, allerdings ist das folgende bis vor ca 6 Monaten gegangen.

Erstmal (ist aber schätze ich eh klar): Du brauchst dafür das DSObst userskript.

Ja mit der neuen Version sollte es wieder funktionieren, weil die Browser vorher unsere Requests geblockt haben.

Setup:
1) Du öffnest DSWorkbench eventuell kommt da von Windows eine Meldung bezüglich Firewall ich würde jetzt sagen dass du die mit ja beantworten musst (bin mir aber nicht zu 100% sicher das man Firewall ausnahmen auf für localhost server braucht)
Sollte keine kommen hast du diese vermutlich schon weggeklickt und alles ist ok.

2) Jetzt gehst du in Workbench in die Einstellungen.
Dort unter Sonstiges.
Jetzt gibt es da unten den Berichteserver. Die Zahl die bei Port steht merkst du dir (bei mir steht 8080 wenn du was anderes hast dann ersetzt du alle folgenden 8080 durch das was du hast)

3) Du gehst mit dem Browser den du benutzen willst auf https://localhost:8080
Jetzt sollte eine Sicherheitswarnung kommen. Jetzt musst du für die Website eine Sicherheitsausnahme hinzufügen (dies ist notwendig um den Schutz des Browsers aus zu trixen ohne das wir Serverresourcen bei einem echten Server brauchen)
Bei Firefox und Chrome macht man das indem man auf erweitert klickt dann bei chrome auf weiter zu der Website und bei Firefox auf Risiko akzeptieren und Fortfahren

Es kann sein, dass sich der Browser dies nicht merkt und du es bei jedem Browser start machen musst sollte aber nicht so sein.

4) Jetzt stellt du in dsobst als url https://localhost:8080 ein
Was du in das User und das Passwort feld hinein schreibst ist dabei völlig egal (wird ignoriert)
und bei hotkey was passendes auswählen

Schritt 4 hab ich aus dem Gedächnis reproduziert (kann Fehler enthalten)

wenn du dabei Probleme haben solltest dann schreib einfach :)

mfg

**Comment by xeddix** [comment]
ich bekomme jetzt mit firefox  vers. 68.02 64bit diese fehlermeldung

Beim Verbinden mit localhost:8080 trat ein Fehler auf. SSL hat einen Eintrag erhalten, der die maximal erlaubte Länge überschritten hat. Fehlercode: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by extremeCrazyCoder** [comment]
Verwendest du die aktuelle Version (3.71)? in der vorherigen gab es einen bug wo der Parser bei direkten Requests gecrasht ist sollte aber mit ( d696ac6 )  gefixt sein.

Sofern du die Sicherheitsausname gemacht hast probier es bitte mal mit dem DSObst Skript, weil selbst die 3.7 die den Bug hatte, auch kein Problem mit echten Reports hatte (eben nur ein Problem wenn man direkt auf die Seite geht)

**Comment by xeddix** [comment]
werd ich gleich probieren, hatte noch die 3.5 version von WB

**Comment by extremeCrazyCoder** [comment]
ok dann kann es nicht gehen, weil der Server bei 3.5 noch ein HTTP server war
11f3188cfc6ebb18621458a9462f3c4f644c77de
9d3878f30de3261ec9f2ab1191b4dc366adff9b9
fcd3ff5391dceb2f362619d77c2bd0919f54f913
Dies hat sich erst in der 3.7 geändert mit den obigen commits

**Comment by xeddix** [comment]
so, vers. 37 installiert

wenn ich jetzt bericht mit E einlesen will passiert eigentlich garnichts....bzw. es öffnet das eingabefeld im browser
hier mal die screenshoots wie ich das eingestellt habe

https://prnt.sc/oz4of2
https://prnt.sc/oz4r65

bei der direkteingabe im browser kommt schon mal etwas anderes

obstCallback("<response><message>The report could not be parsed.</message><data><error>2</error></data></response>");

**Comment by extremeCrazyCoder** [comment]
![grafik](https://user-images.githubusercontent.com/25514433/63940130-2a34f000-ca69-11e9-9f18-053f1e975d4c.png)
Sieht bei mir bisschen anders aus aber ok...

Ich werde das jetzt selber probieren und sage dir dann Bescheid
dauert aber 2:11 bis mein Angriff beim BB ankommt daher hab ich erst dann einen Bericht

Ansonsten schau bitte mal in das Log directory und dort in das File dsworkbench.log
steht dort irgendwo Warning oder Error falls ja kopier bitte die entsprechenden Zeilen und füge sie hier ein

Es kann sein, dass es immer noch bugs gibt. Die neue Version wurde nie richtig getestet...

**Comment by xeddix** [comment]
kein problem....dafür habe ich ein neues
die gleichen farmeinstellungen wie bei der Vers. 3.5 also zum bspl. bei "A" 1späher und 3 lkav, max LZ 300 min
wenn ich jetzt eine oder auch mehrere farmen mit der Einstellung A oder auch B usw. farmen möchte passiert einfach nichts

Truppen eingelesen OK, Gruppen eingelesen auch OK..Farmen eingelesen auch OK

Berichte einlesen mit ctrl a copy funktioniert merkwürdigerweise

fehlermeldungen

2019-08-29 15:07:33,571 - WARN  [Thread-39] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-39'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:34,664 - WARN  [Thread-40] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-40'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:35,168 - WARN  [Thread-41] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-41'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:35,451 - WARN  [Thread-42] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-42'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:35,679 - WARN  [Thread-43] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-43'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:35,880 - WARN  [Thread-44] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-44'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:36,304 - WARN  [Thread-45] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-45'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:36,631 - WARN  [Thread-46] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-46'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:36,839 - WARN  [Thread-47] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-47'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:37,039 - WARN  [Thread-48] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-48'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:37,408 - WARN  [Thread-49] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-49'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:38,463 - WARN  [Thread-50] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-50'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:52,847 - WARN  [Thread-51] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-51'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:53,451 - WARN  [Thread-52] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-52'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:54,149 - WARN  [Thread-53] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-53'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:07:54,371 - WARN  [Thread-54] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-54'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
2019-08-29 15:15:49,114 - WARN  [ClipboardMonitor] - (de.tor.tribes.util.parser.GroupParser [73]) - Failed to parse group info from village renamer data

**Comment by xeddix** [comment]
das mit dem fehlereinfügen war keine gute idee da fehlt ja die hälfte:

[dslog,txt.txt](https://github.com/Torridity/dsworkbench/files/3555753/dslog.txt.txt)

**Comment by extremeCrazyCoder** [comment]
Danke das sind aber viele :)

hab mich schon gewundert das es so plotzlich aufhört

**Comment by extremeCrazyCoder** [comment]
ok haben nur die letzten 2 Zeilen gefehlt. Wir haben da 2 Fehlermeldungen (die sich einfach mehrfach wiederholen)
DIe erste kann der Grund für das nicht funktionieren des Farmmanagers sein:
2019-08-29 15:07:33,571 - WARN  [Thread-39] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'Thread-39'
java.lang.NullPointerException: null
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.getSelectedFarmGroup(DSWorkbenchFarmManager.java:120) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.farm(DSWorkbenchFarmManager.java:910) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager.access$2000(DSWorkbenchFarmManager.java:85) ~[Core-3.71.jar:3.71]
	at de.tor.tribes.ui.views.DSWorkbenchFarmManager$25.run(DSWorkbenchFarmManager.java:811) ~[Core-3.71.jar:3.71]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
https://github.com/Torridity/dsworkbench/blob/e99bf3662cdf8778a191cbd602b636aa0b4b6125/Core/src/main/java/de/tor/tribes/ui/views/DSWorkbenchFarmManager.java#L120 von dieser Stelle kommt die Exception

Kannst du mal bitte schauen ob du irgendwo einstellen kannst mit welcher Gruppe du farmen willst diese Einstellung dürfte fehlen ich kann sie derzeit nur selber nicht finden

die 2. hätte ich jetzt mal ignoriert, weil die eher unwichtig aussieht
die kommt von dem Gruppenparser, nachdem ich aber noch nie etwas von Problemen mit diesem gehört hab würde ich das ignorieren.
Du kannst sicherheitshalber nachsehen ob die Gruppen eingelesen wurden
2019-08-29 15:15:49,114 - WARN  [ClipboardMonitor] - (de.tor.tribes.util.parser.GroupParser [73]) - Failed to parse group info from village renamer data
Mir fällt gerade auf das dies sogar von einem Parser kommt der seit 4-7 Jahren eigentlich nicht mehr gebraucht wird, weil Die Stämme das Format geändert hat und es bereits einen neuen gibt...
Also würde ich sagen komplett egal

**Comment by extremeCrazyCoder** [comment]
![grafik](https://user-images.githubusercontent.com/25514433/63946138-ec3dc900-ca74-11e9-8340-3676566a203f.png)
Hier musst du eine Gruppe einstellen

**Comment by xeddix** [comment]
ja da hst du recht, hab ich jetzt gefunden und hab ich gleich mal probiert und farmtrupps schicken geht auch, noch nicht ganz so wie ich will aber da werd ich noch probieren

**Comment by xeddix** [comment]
gruppen werden eingelesen, ist ok

**Comment by extremeCrazyCoder** [comment]
ich hab das Problem, dass standardmäßig mist ausgewäht ist gefixt mit 55067e6d35b45fae3d850acc0a5f9c4987bf39a0
ich würde eventuell dann nochmal eine neue Version machen wenn der Farmmanager jetzt geht

**Comment by extremeCrazyCoder** [comment]
![grafik](https://user-images.githubusercontent.com/25514433/63950839-05e30e80-ca7d-11e9-88d2-4a85715004d8.png)
![grafik](https://user-images.githubusercontent.com/25514433/63950860-0e3b4980-ca7d-11e9-9579-207185806d33.png)
![grafik](https://user-images.githubusercontent.com/25514433/63950988-45a9f600-ca7d-11e9-8679-570c0d90a24f.png)

Also bei mir geht es mehr oder weniger (irgendwas passt mit der Beute nicht...)

**Comment by xeddix** [comment]
super, im DS Obst script muss glaube ich auch noch was geändert werden, ich such grade im forum habs aber noch nicht gefunden

**Comment by extremeCrazyCoder** [comment]
welches addon verwendest du denn? Beim Firefox geht nur noch das Tampermonkey adddon nachedem Greasemonkey mit einer neuen Version inkompalitäten eingebaut hat

**Comment by xeddix** [comment]
ja ich benutze jetzt auch Tampermonkey

**Comment by extremeCrazyCoder** [comment]
Ändert sich der Text oben zu einem wird gesendet?
![grafik](https://user-images.githubusercontent.com/25514433/63952218-77bc5780-ca7f-11e9-8ffc-e860957aa9d0.png)
oder bleibt er so wie in deinem Bild: https://prnt.sc/oz4of2 ?

Falls er so bleibt kann ich dir jetzt auch nicht weiter helfen. im anderen Fall kann es noch an Workbench liegen und dann können wir es genauer untersuchen

**Comment by xeddix** [comment]
da taucht leider garnichtsmehr auf seit ich das Obst Script vorher neu installiert habe, da war im forum mal ein beitrag das man da noch was ändern muss und das suche ich gerade

**Comment by xeddix** [comment]
ok, habs gefunden und geändert jetzt tauch auch wieder : ........**warte auf befehl auf**

ich drücke auf "E" und nichts passiert..so langsam zweifle ich an mir selbst

**Comment by xeddix** [comment]
also so wie auf
https://prnt.sc/oz4of2

**Comment by extremeCrazyCoder** [comment]
probier vielleicht mal das du ein kleines e eingibst oder vorher irgendwo beim Bericht hinklickst wo nix passiert (damit der richtige teil vom Fenster aktiv ist)
wenn du vorher aber aus der Berichteübersicht gekommen bist dann müsste eh schon das richtige aktiv sein....

als frage was hast du denn geändert?

**Comment by xeddix** [comment]
hab ich jetzt alles versucht, er sendet einfach nicht
änderung ist jetzt lediglich die neue WB version

**Comment by xeddix** [comment]
[dsworkbench.txt](https://github.com/Torridity/dsworkbench/files/3556514/dsworkbench.txt)

**Comment by extremeCrazyCoder** [comment]
Was auch immer du gemacht hast so wie es aussieht funktioniert das mit dem Firefox doch (sonst könntest du im Log nicht die URL mit dem Bericht haben
kannst du bitte mal schauen ob der Bericht eingelesen wurde?

Ich habs gerade bei mir mit deiner URL getestet und das ist dabei raus gekommen:
![Bildschirmfoto vom 2019-08-29 19-27-11](https://user-images.githubusercontent.com/25514433/63962625-74cb6200-ca93-11e9-8964-0bfcae163381.png)

**Comment by xeddix** [comment]
hab ich jetzt nicht ganz verstanden wie du das meinst, die berichte landen alle im "normalen" Berichteordner, Tabs hab ich nur dann mehrere wen ich die angriffe losschicke

**Comment by xeddix** [comment]
jetzt hab ich was merkwürdiges gesehen
https://prnt.sc/oz9tce
wenn ich einen bericht öffne
dann bei DS-OBST Berichteeinleser - Einstellungen nochmals manuell ein "E"  oder "e" eingebe dann funktioniert das

**Comment by extremeCrazyCoder** [comment]
die Berichte sollten eigentlich wenn sie zum Farmanager gehören im Farmanager ordner landen das wundert mich gerade

funktioniert der hotkey jetzt generell oder musst du bei jedem bericht nochmals das e eintragen?

**Comment by xeddix** [comment]
also habs nochmals probiert und  tatsächlich, ich muss jedesmal das e nochmal eintragen
also ich hab da keinen extra ordner, ist der ganz normale ordner wo alle berichte landen

**Comment by extremeCrazyCoder** [comment]
mit Ordner meinte ich wenn du in workbench auf Berichte gehst dann hast du oben die 2 Reiter:
![grafik](https://user-images.githubusercontent.com/25514433/63967237-3dfa4980-ca9d-11e9-891f-da4ec63b1e4c.png)

Alles was der Farmmanager erkennt sollte eigentlich unter Farmberichte landen und nicht unter default...

zu deinem Problem mit dem OBST Skript kann ich nur sagen: hast du irgendwelche speziellen Privacy settings? wenn nicht weiß ich auch nicht mehr weiter. Du kannst es eventuell im Forum probieren die erfolgsaussichten sind aber extrem gering

**Comment by xeddix** [comment]
achso, jetzt weiss ich was du meinst:) heute ist nicht mein tag
ja berichte sind im ordner farmberichte von den letzten 2 stunden etwa

kann es sein das immer noch was im DS-OBST Berichteeinleser nicht stimmt weil settings müssten alle standard sein

**Comment by extremeCrazyCoder** [comment]
Ich weiß es nicht wirklich ob da noch ein Problem bei dem Skript vor liegt mich wundert dieses Verhalten selber jetzt auch und ich weiß nicht was du da tun kannst.

Ich mein du könntest es theoretisch mit einem anderen Browser probieren aber das ist das letzte was mit einfällt

**Comment by xeddix** [comment]
werd ich am wochenende mal tun sowas hab ich auch noch nicht erlebt
aber erstmal vielen dank für die mühe

**Comment by extremeCrazyCoder** [comment]
Ich habe jetzt eine Inoffizielle Version mit den Fixes für die von dir gemeldeten Bugs gebaut.
Sollte da nix mehr dazu kommen in nächster Zeit wird da irgendwann eine Offizielle draus.
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.71-patch-1

**Comment by xeddix** [comment]
es funktioniert die berichte mit einem tastendruck einzulesen
was habe ich gemacht?
ich habe jetzt von Firefox auf Opera umgestellt.
alle scripte wieder installiert und die einstellungen gemacht, was passiert?
es kommt die meldung: wird gesendet...und nichts passiert
so jetzt erstmal frust und Opera wieder deinstalliert und mal einen tag lang nichts gemacht
dann habe ich Opera nochmals installiert einfach mehr aus Jux und guter Laune das gleiche gemacht wie voher auch schon mal und....es funktioniert auf Anhieb
keine Ahnung warum und wieso aber funktioniert einfach super

**Comment by extremeCrazyCoder** [comment]
:smiley: klingt super
falls damit dann alles geklärt ist dann schließ bitte das Issue

btw: Ich kann jetzt natürlich auch nicht sagen warum es beim ersten mal nicht geklappt hat aber eventuell schaust du mal in den Log von Workbench ob von damals irgendwelche Fehler drinnen stehen. oder als Frage: hast du es mit dem gleichen Bericht oder einem unterschiedlichen Probiert?
Es kann sein, dass manche Berichte zu einem Bug führen und andere nicht. In dem Fall hätte ich dann gern den Log damit ich das Fixen kann
