### ISSUE TITLE
Kirchen und Wachtürme lassen sich nicht einzeichnen

### ISSUE THREAD

**Issue by Fear81** [Torridity/dsworkbench#76]
Ich hab bei WB 3.72 das Problem das mir die Wachtürme und Kirchen nicht eingezeichnet werden. Jemand ne Idee?

**Comment by extremeCrazyCoder** [comment]
Ideen schon :D

Schau bitte mal ob die Kirchen / Wachtürme in den Übersichten gespeichert werden falls ja:
Schau bitte ob du die Kirchen / Wachtürme eventuell durch ebeneneinstellungen ausgeblendet hast (oben links auf die Axt drauf drücken -> dann irgendwas mit ebenen)
Probier mal Workbench neu zu starten

falls nein:
Wie erstellst du die Kirche / den Wachturm?

In beiden Fällen
Schau bitte mal ob im log file (ordner logs -> dsworkbench.log) irgendwelche exceptions drinnen stehen

**Comment by dlfkjahliuerlkjna** [comment]
Ich habe das selbe Problem für die meisten Dörfer. Wenn sich ein Wachturm Radius nicht zeichnen lässt befindet sich in der log Datei dieses:
WARN  [AWT-EventQueue-0] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null

**Comment by extremeCrazyCoder** [comment]
Hm das hilft leider nicht wirklich
ich kann mal probieren das ganze zu testen ob ich was finde (ich geb das also mal auf meine TODO aber ich weiß nicht ob ich da was finde)

@dlfkjahliuerlkjna kannst du bitte die nächsten 3-4 Zeilen dir hinter deinem Code kommen noch kopieren (oder noch besser alles bis wieder eine Zeit vorne ist; je nachdem was es ist können das 10-20 Zeilen sein)

**Comment by dlfkjahliuerlkjna** [comment]
In der Regel ist das alles was bis zum nächsten Zeitstempel erscheint. In manchen seltenen Fallen ist danach noch dieses zu finden:
```
	at de.tor.tribes.types.TimeSpan.isValidAtExactTime(TimeSpan.java:108) ~[Core-3.72.jar:3.72]
	at de.tor.tribes.types.TimeSpan.isValidAtSpecificDay(TimeSpan.java:116) ~[Core-3.72.jar:3.72]
	at de.tor.tribes.types.TimeSpan.toString(TimeSpan.java:287) ~[Core-3.72.jar:3.72]
	at javax.swing.JList.getNextMatch(Unknown Source) ~[?:1.8.0_211]
	at javax.swing.plaf.basic.BasicListUI$Handler.keyTyped(Unknown Source) ~[?:1.8.0_211]
	at java.awt.AWTEventMulticaster.keyTyped(Unknown Source) ~[?:1.8.0_211]
	at java.awt.AWTEventMulticaster.keyTyped(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.processKeyEvent(Unknown Source) ~[?:1.8.0_211]
	at javax.swing.JComponent.processKeyEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source) ~[?:1.8.0_211]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_211]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_211]
```
Eine vollständige log Datei befindet sich im Anhang.
[dsworkbench.log](https://github.com/Torridity/dsworkbench/files/4641851/dsworkbench.log)

**Comment by extremeCrazyCoder** [comment]
Danke für den Log das hilft (und verwirrt mich, weil anscheinend das logging fehlerhaft ist)

Hier alle Fehlermeldungen aus dem Log:

- WARN  [StartupTimer] - (de.tor.tribes.util.ServerSettings [97]) - Unable to read bonus type
  - Vermutlich hat DS hier irgendwas geändert, das wird aber eh korrekt abgefangen -> egal
- ERROR [StartupTimer] - (de.tor.tribes.util.sos.SOSManager [74]) - Failed to load SOS requests
  - Sieht erstmal nach irgendwie beschädigten save datein aus sollte idr mit einem restart gefixt werden (weil dann gespeichert und geladen wird)
- WARN [AWT-EventQueue-0] - (de.tor.tribes.ui.renderer.map.MapRenderer [271]) - Failed to render group layer ---- java.util.ConcurrentModificationException: null
  - Das sollte nicht auftreten kann aber sein, dass da gerade unglücklich mehrere Threads sich getroffen haben
- ERROR [BackupTimer] - (de.tor.tribes.ui.windows.BackupTask [3097]) - Failed to create backup
  - Bug gefixt mit 2f260bd7211b33edc970597f38fe84c0c0eb6217 dadurch stürtzt workbench bei dem schließen ab und es werden die beschädigten save datein von oben nie repariert
- [AWT-EventQueue-0] - (de.tor.tribes.ui.windows.DSWorkbenchSplashScreen$ExceptionHandler [430]) - Unhandled exception in thread 'AWT-EventQueue-0' java.lang.NullPointerException: null
  - hier weiß ich nicht ob das zwei verschiedene Fehler sind oder einer, würde aber intuitiv eher sagen unterschiedliche. Die muss ich mir auch anschauen
  - https://github.com/Torridity/dsworkbench/blob/b46e925720ff2e54440920949c6dda089c3a03b5/Core/src/main/java/de/tor/tribes/types/TimeSpan.java#L108
  - Ideen zur zweiten: Village gelöscht die einen WT hatte -> NPE bei KnownVillage -> NPE WT drawing?

**Comment by extremeCrazyCoder** [comment]
So ich sollte die Fehler behoben haben (hab die hinteren beiden Fehler gefixt)

Neue Version: https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-5
